### ISSUE TITLE
Choix de la langue?

### ISSUE THREAD

**Issue by emmanuelCarre** [DockerLyon/community#2]
Bonjour,

C'est une question bateau, mais quelle langue utiliser pour ce dépôt? Étant donné que c'est un pour un événement local, je choisirai la langue locale: français.

Qu'en pensez-vous?

**Comment by xinity** [comment]
Tu as raison, je me suis fait la reflexion quand j'ai init le dépot.

Je souhaite que cela puisse aussi servir à d'autre que la communauté FR pour exemple d'organisation du coup, je me tate j'avoue.

Si cela te va, on reste en anglais, quitte à préciser la raison de ce choix de langue :)
@emmanuelCarre deal ?

**update**:
v'la maintenant que j'écris les issue en français :(
bon aller, on fige la langue en anglais ?

**Comment by emmanuelCarre** [comment]
Approved for english. Just, I hope it will be not a problem to us users.

I will rework my pull request #3.

**Comment by xinity** [comment]
deal !
Issue closed !
