### ISSUE TITLE
Blog du DockerLyon

### ISSUE THREAD

**Issue by xinity** [DockerLyon/community#6]
aprés pas mal de test en tout genre, Hugo semble être une bonne solution, simple, rapide et efficace.

Je propose de créer un WorkFlow utilisant TravisCI par exemple pour publier notre blog sur dockerlyon.github.com.

l'objectif est que tout le monde puisse participer à la vie du blog via des PR sur un dépot central, celui servant de source à la generation du site statique qui sera accessible sur dockerlyon.github.com

Si cela convient, je documenterais le workflow complement dans un fichier md à part.

**Comment by emmanuelCarre** [comment]
I trust you, I have no significant experience for the tool to use.

For the workflow, I validate :)

**Comment by xinity** [comment]
Cool !

Let's roll, i'll create some documentation about the workflow and how it works exacly so anyone could contribute if they are willing to :)
